travis:
  secure:
    BINSTAR_TOKEN: G5VoEyWY2cHNv0xiwo4l9SHrAQLkXl8lCyJ/maG7K5reYJ2V3b7+D5JBv/0HJxEBlhy6W6IxP37+6lwvhbnj7kHjm36C86L9RsULF9ZSoXBPcE6tr2vv8za9+2PVpNK/X7YdETnmEfVTgSwMS1mya+YjJfR1LuACc04Xtq/FtMplWnmHmFeXphTAtRYnQ9/IfvmHULuAKY8mqFukZJeDkQlnlN9VXVrnueb7pu8mufjlP6+r31he0Ns/FcijFkN6uV8R3AkMNxdgaTL+YfIyq/BgG8ITgbXgnPZ587BKQq7RM2y/D4hu96w5BONpWUYOQVpfJnnZEjI+8CaiZenYyw9Bk2qkGsdWfEc3hZNj7XEPHKwWi/ScSeIisVDNZxpj/ZfSrvHKO44/RVYHgLRuweVHJf3B7OUv1Mes8s41eoMCORunwfcj9fSbwdonPpxalysI94TP1JOdFq4Kf/Tkzo8jYqaRQ5GzD3WG5nqLfOYQhzYlnEdQl8YaCznUEWFTiw8xymPuAuBvGSB0pNIZfPDD+RFWDIsGUA39tlNuzSne9A5jApCjgHzXBxauqUyOPmgx9GdmTusiYyWfXjUQD8VCYmyacdAHaK8QiUxcZ7qdGGwLYQKdkkN/2R8/eClFz9sGJQkebBH5vY+F9SbkBp/E43WNLS0ODr3mTyv+zpo=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
